# Generated by Django 4.1 on 2022-09-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_review_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='review_associate',
        ),
    ]
